"""Joint-name mapping between a source qpos vector and the A3 policy view.

Plan sections 18 and 85 are explicit: **never** assume that the first 29 entries
of some qpos array are the policy joints.  Every conversion goes through joint
*names* resolved against the A3 contract, with an explicit alias table for name
variants (``left_hip_pitch`` vs ``left_hip_pitch_joint``).

The mapping config lives in ``configs/a3_joint_map.yaml`` and is generated by
``tools/make_joint_map.py``.
"""

from __future__ import annotations

import functools
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import yaml

from ..contract import load_contract

BRIDGE_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_MAP_PATH = BRIDGE_ROOT / "configs" / "a3_joint_map.yaml"

__all__ = ["A3JointMap", "load_joint_map", "JointMapError"]


class JointMapError(RuntimeError):
    """Raised when a source joint vector cannot be mapped onto the policy view."""


@dataclass(frozen=True)
class A3JointMap:
    policy_joint_names: tuple[str, ...]
    aliases: dict[str, str]  # source name -> policy name
    forbidden_source_names: tuple[str, ...]
    raw: dict
    path: Path

    @property
    def n_joints(self) -> int:
        return len(self.policy_joint_names)

    def canonical_source_name(self, source_name: str) -> str | None:
        """Map one source joint name onto a policy joint name (or None)."""
        if source_name in self.policy_joint_names:
            return source_name
        return self.aliases.get(source_name)

    def build_index_map(self, source_names) -> tuple[np.ndarray, list[str], list[str]]:
        """Resolve ``source_names`` against the policy view.

        Returns ``(index, resolved_source_names, missing_policy_joints)`` where
        ``index[i]`` is the position in ``source_names`` of policy joint ``i``.
        """
        source_names = [str(n) for n in source_names]
        if len(set(source_names)) != len(source_names):
            duplicates = sorted({n for n in source_names if source_names.count(n) > 1})
            raise JointMapError(f"source joint names contain duplicates: {duplicates}")

        lookup: dict[str, int] = {}
        for position, name in enumerate(source_names):
            canonical = self.canonical_source_name(name)
            if canonical is None:
                continue
            if canonical in lookup:
                raise JointMapError(
                    f"both {source_names[lookup[canonical]]!r} and {name!r} map to {canonical!r}"
                )
            lookup[canonical] = position

        missing = [name for name in self.policy_joint_names if name not in lookup]
        if missing:
            raise JointMapError(
                "source joint vector is missing policy joints: "
                f"{missing} (available: {sorted(source_names)})"
            )
        index = np.asarray([lookup[name] for name in self.policy_joint_names], dtype=np.int64)
        resolved = [source_names[i] for i in index]
        return index, resolved, []

    def map_vector(self, values: np.ndarray, source_names) -> np.ndarray:
        """Reorder an arbitrary joint vector into policy order by name."""
        values = np.asarray(values, dtype=np.float64).reshape(-1)
        if values.size != len(list(source_names)):
            raise JointMapError(
                f"value vector length {values.size} != {len(list(source_names))} source joint names"
            )
        index, _, _ = self.build_index_map(source_names)
        return values[index]

    def assert_no_forbidden(self, source_names) -> None:
        """Fail if head/passive joints are present in a *policy* vector."""
        used = [str(n) for n in source_names]
        leaked = [n for n in used if n in set(self.forbidden_source_names)]
        if leaked:
            raise JointMapError(f"policy vector must not contain: {leaked}")


@functools.lru_cache(maxsize=4)
def _load_cached(path_str: str, mtime_ns: int) -> A3JointMap:
    del mtime_ns
    with open(path_str, "r", encoding="utf-8") as handle:
        doc = yaml.safe_load(handle)
    contract = load_contract()

    policy_names = tuple(doc["policy_joint_names"])
    if policy_names != contract.policy_joint_names:
        raise JointMapError(
            "configs/a3_joint_map.yaml policy_joint_names do not match the A3 contract; "
            "run: python tools/make_joint_map.py"
        )
    if len(policy_names) != 29 or len(set(policy_names)) != 29:
        raise JointMapError("policy joint view must be 29 unique joints")

    aliases = {str(k): str(v) for k, v in (doc.get("aliases") or {}).items()}
    for source, target in aliases.items():
        if target not in policy_names:
            raise JointMapError(f"alias {source!r} points at unknown policy joint {target!r}")
        if source in policy_names:
            raise JointMapError(f"alias {source!r} shadows a policy joint name")

    forbidden = tuple(doc.get("forbidden_source_names", ()))
    for name in forbidden:
        if name in policy_names:
            raise JointMapError(f"forbidden joint {name!r} appears in the policy view")

    return A3JointMap(
        policy_joint_names=policy_names,
        aliases=aliases,
        forbidden_source_names=forbidden,
        raw=doc,
        path=Path(path_str),
    )


def load_joint_map(path: Path | str | None = None) -> A3JointMap:
    resolved = Path(path).expanduser() if path else DEFAULT_MAP_PATH
    if not resolved.is_file():
        raise JointMapError(
            f"joint map not found at {resolved}. Run: python tools/make_joint_map.py"
        )
    return _load_cached(str(resolved), resolved.stat().st_mtime_ns)
