#!/usr/bin/env python3
"""Generate the C++ joint-order table for the A3 teleop command bridge (plan §18/§60).

`/ta/whole_body_command` (the channel the official A3 runtime already consumes via
``A3TeleopReference``) carries the **policy view** order, as documented by
``ConvertTaWholeBodyCommand`` in ``a3_teleop_reference.cpp``:

    waist[0..2], left arm[3..9], right arm[10..16], left leg[17..22], right leg[23..28]

``A3_REFERENCE_V1`` instead carries the **encoder (il)** order.  The two are a real
permutation, so the C++ adapter must never index by position: this tool emits both
names and both directions of the permutation straight from the bridge contract
(``generated/a3_contract.json``), which itself derives them from the A3 CSV header
and the MJCF.

Usage:
    python tools/make_cpp_joint_order.py [--out PATH]
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

BRIDGE_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BRIDGE_ROOT / "src"))

from a3_teleop_bridge.contract import load_contract  # noqa: E402

DEFAULT_OUT = (
    Path.home()
    / "a3_teleop_ws"
    / "sonic_for_a3"
    / "gear_sonic_deploy/src/g1/g1_deploy_onnx_ref/include/a3_deploy/a3_teleop_joint_order.hpp"
)

TEMPLATE = '''// Auto-generated by a3_teleop_bridge/tools/make_cpp_joint_order.py
// DO NOT EDIT BY HAND.
//
// Source: {source} (sha256 {sha})
// Generated: {stamp}
//
// Two distinct 29-joint orders are in play on the robot:
//   * `kA3IlJointNames`      -- the order of A3_REFERENCE_V1 (encoder / IsaacLab)
//   * `kA3PolicyJointNames`  -- the order of /ta/whole_body_command and of the
//                               A3TeleopFrame that A3TeleopReference consumes
//                               (waist[0..2], left arm[3..9], right arm[10..16],
//                                left leg[17..22], right leg[23..28])
//
// The permutations below are the only sanctioned way to cross between them.
#pragma once

#include <array>
#include <cstddef>

namespace a3_deploy {{

inline constexpr std::size_t kA3TeleopJointCount = {nj};

// Policy view order (what the runtime tokenizer expects).
inline const char* const kA3PolicyJointNames[kA3TeleopJointCount] = {{
{policy_names}
}};

// Encoder (il) order (what A3_REFERENCE_V1 carries).
inline const char* const kA3IlJointNames[kA3TeleopJointCount] = {{
{il_names}
}};

// kA3PolicyToIlIndex[policy_index] = index inside the wire payload.
inline constexpr std::array<int, kA3TeleopJointCount> kA3PolicyToIlIndex = {{{policy_to_il}}};

// kA3IlToPolicyIndex[wire_index] = index inside the policy view.
inline constexpr std::array<int, kA3TeleopJointCount> kA3IlToPolicyIndex = {{{il_to_policy}}};

}}  // namespace a3_deploy
'''


def portable_source(value) -> str:
    """Render a source path for the generated header without a machine path."""
    candidate = Path(str(value))
    try:
        return "$A3WS/" + str(candidate.resolve().relative_to(BRIDGE_ROOT.parent))
    except ValueError:
        return str(candidate)


def main(argv: list[str] | None = None) -> int:
    import hashlib

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default=str(DEFAULT_OUT))
    parser.add_argument(
        "--contract",
        default=str(BRIDGE_ROOT / "generated" / "a3_contract.json"),
    )
    args = parser.parse_args(argv)

    contract = load_contract()
    policy = list(contract.policy_joint_names)
    il = list(contract.il_joint_names)
    policy_to_il = list(contract.policy_to_il_index)
    if len(policy) != 29 or len(il) != 29:
        raise SystemExit(f"expected 29 joints, got policy={len(policy)} il={len(il)}")
    il_to_policy = [0] * 29
    for p, i in enumerate(policy_to_il):
        il_to_policy[i] = p
    # a permutation must round-trip, and the names must agree with it
    assert all(il_to_policy[i] == p for p, i in enumerate(policy_to_il))
    for p, i in enumerate(policy_to_il):
        assert policy[p] == il[i], f"name mismatch at policy {p}: {policy[p]} != {il[i]}"

    raw = Path(args.contract).read_bytes()
    text = TEMPLATE.format(
        source=portable_source(args.contract),
        sha=hashlib.sha256(raw).hexdigest(),
        stamp=datetime.now(timezone.utc).isoformat(timespec="seconds"),
        nj=len(policy),
        policy_names="\n".join(f'    "{n}",' for n in policy),
        il_names="\n".join(f'    "{n}",' for n in il),
        policy_to_il=", ".join(str(v) for v in policy_to_il),
        il_to_policy=", ".join(str(v) for v in il_to_policy),
    )
    out = Path(args.out).expanduser()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    print(f"wrote {out}")
    print(f"  policy_to_il[:5] = {policy_to_il[:5]}")
    print(f"  round-trip/per-name checks: OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
