#!/usr/bin/env python3
"""Generate the C++ joint-limit table for the A3 reference watchdog (plan §61).

The A3 C++ runtime must not hard-code limits by hand: this tool turns
``generated/a3_joint_limits.yaml`` (itself extracted from the MJCF/URDF/deploy
header) into a constexpr header used by ``a3_reference_stream.cpp``.

The table is written in the **encoder (il) joint order**, matching the payload of
``A3_REFERENCE_V1``.

Usage:
    python tools/make_cpp_reference_limits.py [--out PATH]
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml

BRIDGE_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BRIDGE_ROOT / "src"))

from a3_teleop_bridge.contract import load_contract  # noqa: E402

DEFAULT_OUT = (
    Path.home()
    / "a3_teleop_ws"
    / "sonic_for_a3"
    / "gear_sonic_deploy/src/g1/g1_deploy_onnx_ref/include/a3_deploy/a3_reference_limits.hpp"
)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default=str(DEFAULT_OUT))
    parser.add_argument(
        "--limits",
        default=str(BRIDGE_ROOT / "generated" / "a3_joint_limits.yaml"),
    )
    parser.add_argument(
        "--position-tolerance",
        type=float,
        default=0.02,
        help="rad of slack allowed before a reference is rejected",
    )
    parser.add_argument(
        "--velocity-scale",
        type=float,
        default=1.05,
        help="multiplier applied to the hardware velocity limit",
    )
    args = parser.parse_args(argv)

    contract = load_contract()
    doc = yaml.safe_load(Path(args.limits).read_text(encoding="utf-8"))
    joints = doc["joints"]
    il_names = contract.il_joint_names

    lower, upper, velocity = [], [], []
    for name in il_names:
        entry = joints[name]
        lower.append(float(entry["position_lower"]))
        upper.append(float(entry["position_upper"]))
        velocity.append(float(entry["velocity_limit"]))

    def fmt(values, per_line=5):
        lines = []
        for i in range(0, len(values), per_line):
            chunk = ", ".join(f"{v:.9g}f" for v in values[i : i + per_line])
            lines.append("    " + chunk + ",")
        return "\n".join(lines)

    text = f"""// Auto-generated by a3_teleop_bridge/tools/make_cpp_reference_limits.py
// DO NOT EDIT BY HAND.
//
// Source: {args.limits}
// Generated: {datetime.now(timezone.utc).isoformat(timespec="seconds")}
//
// Joint order is the ENCODER (il) order of A3_REFERENCE_V1.
#pragma once

#include <array>
#include <cstddef>

namespace a3_deploy {{

struct A3ReferenceLimits {{
  static constexpr std::size_t kJoints = {len(il_names)};
  const char* const* joint_names;
  std::array<float, kJoints> position_lower;
  std::array<float, kJoints> position_upper;
  std::array<float, kJoints> velocity;
  float position_tolerance;
  float velocity_scale;
}};

inline constexpr std::size_t kA3ReferenceJointCount = A3ReferenceLimits::kJoints;
inline const char* const kA3ReferenceJointNames[kA3ReferenceJointCount] = {{
{chr(10).join('    "' + name + '",' for name in il_names)}
}};

inline constexpr A3ReferenceLimits kA3ReferenceLimits = {{
    kA3ReferenceJointNames,
    {{{{
{fmt(lower)}
    }}}},
    {{{{
{fmt(upper)}
    }}}},
    {{{{
{fmt(velocity)}
    }}}},
    {args.position_tolerance:.6g}f,
    {args.velocity_scale:.6g}f,
}};

}}  // namespace a3_deploy
"""

    out = Path(args.out).expanduser()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    print(f"wrote {out}")
    print(f"  joint order : encoder (il), {len(il_names)} joints")
    print(f"  positions   : [{min(lower):+.4f}, {max(upper):+.4f}] rad")
    print(f"  velocities  : [{min(velocity):.3f}, {max(velocity):.3f}] rad/s")
    print(f"  tolerance   : {args.position_tolerance} rad, velocity x{args.velocity_scale}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
